# Generated by Django 6.1.2 on 2026-10-08 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=64)),
                ('symbols', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('starting_cash', models.FloatField()),
                ('ending_value', models.FloatField()),
                ('trade_count', models.IntegerField(default=0)),
                ('max_drawdown_pct', models.FloatField(default=0.0)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(default=1000.0)),
                ('starting_cash', models.FloatField(default=1000.0)),
                ('active_strategy', models.CharField(default='sma_crossover', max_length=64)),
                ('watch_symbol', models.CharField(default='AAPL', max_length=16)),
                ('fee_bps', models.FloatField(default=0.0)),
                ('chart_range', models.CharField(default='90', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('mood', models.CharField(choices=[('neutral', 'Neutral'), ('confident', 'Confident'), ('cautious', 'Cautious'), ('fomo', 'FOMO'), ('lesson', 'Lesson learned')], default='neutral', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.FloatField()),
                ('cash', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trading.portfolio')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=8)),
                ('target', models.FloatField()),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('symbol', models.CharField(max_length=16)),
                ('shares', models.FloatField()),
                ('price', models.FloatField()),
                ('fee', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('strategy', models.CharField(blank=True, max_length=64)),
                ('realized_pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('shares', models.FloatField(default=0.0)),
                ('avg_cost', models.FloatField(default=0.0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='trading.portfolio')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
